Feature/iteration 1/b 5 implement sorting
Geodezist/movieland pull request #10
Opened 2018-11-22 10:15 UTC by Geodezist

2018-11-22 23:15 UTC, Rooman requested changes

2018-11-22 23:15 UTC, Rooman commented on src/main/java/ua/com/bpgdev/movieland/dao/jdbc/JdbcMovieDao.java
> +    private String queryBuilder(String rawQuery, ParameterInfo parameterInfo) {
Представь что от правильности работы этого метода зависит благополучие твоего бизнеса. Ты или продолжаешь существовать или банкрот. 

Уверен что ему можно доверять? Или стоит написать тест?

2018-11-22 23:15 UTC, Rooman commented on src/main/java/ua/com/bpgdev/movieland/dao/jdbc/JdbcMovieDao.java
> +    private String queryBuilder(String rawQuery, ParameterInfo parameterInfo) {
Можно не писать интеграционные или функциональные тесты. 
Но отсутвсие юнит тестов на логику ифов\циклов -> reject.

2018-11-22 23:15 UTC, Rooman commented on src/main/java/ua/com/bpgdev/movieland/entity/Movie.java
> +    public static final Comparator<Movie> MOVIE_RATING_DESCENDING_COMPARATOR =
1. Такое в сущности не храним. Можно создать класс MovieComparators. 
2. Зачем нам вообще эти компараторы? Ты же вроде на уровне базы сортируешь

2018-11-22 23:15 UTC, Rooman commented on src/main/java/ua/com/bpgdev/movieland/common/ParameterInfo.java
> +    public Map<SortingField, SortingOrder> getParameters() {
Предлагаю еще пару методов добавить типо 
addSort etc

2018-11-22 23:15 UTC, Rooman commented on src/main/java/ua/com/bpgdev/movieland/common/ParameterInfo.java
> +    public Map<SortingField, SortingOrder> getParameters() {
А мапу напрямую не отдавать. 
Зачем им знать что у нас мапа внутри?

2018-11-22 23:15 UTC, Rooman commented on src/main/java/ua/com/bpgdev/movieland/service/DefaultMovieService.java
> +    public DefaultMovieService(@Qualifier("jdbcMovieDao") MovieDao movieDao) {
А без квалифаера?

2018-11-22 23:15 UTC, Rooman commented on src/main/java/ua/com/bpgdev/movieland/web/controller/MovieController.java
> +    public List<Movie> getAll(@RequestParam(value = "rating") @Nullable String ratingSortingOrder,
Убераем @Nullable. Она нужна для утилитарных методов что бы понимать какие параметры могут быть налами. 
Можем сделать так что бы параметром сразу SortOrder приходил?

2018-11-22 23:15 UTC, Rooman commented on src/main/java/ua/com/bpgdev/movieland/web/controller/MovieController.java
> +            parameterInfo.getParameters().put(SortingField.RATING, SortingOrder.valueOf(ratingSortingOrder.toUpperCase()));
Не используй стандартный valueOf. Используй свой кастомный метод. Как мы делали в веб сервера статическом например

2018-11-22 23:15 UTC, Rooman commented on src/main/java/ua/com/bpgdev/movieland/web/controller/MovieController.java
> +            parameterInfo.getParameters().put(SortingField.RATING, SortingOrder.valueOf(ratingSortingOrder.toUpperCase()));
У нас есть конкретные варианты сортировок. Есть ли валидация на правильность этих параметров?

2018-11-23 13:02 UTC, Geodezist commented on src/main/java/ua/com/bpgdev/movieland/entity/Movie.java
> +    public static final Comparator<Movie> MOVIE_RATING_DESCENDING_COMPARATOR =
Компараторы делал для тестов. Удобно.

2018-11-23 13:03 UTC, Geodezist commented on src/main/java/ua/com/bpgdev/movieland/common/ParameterInfo.java
> +    public Map<SortingField, SortingOrder> getParameters() {
Переделал вообще.

2018-11-23 14:28 UTC, merged